name: Test cache1
on:
  workflow_dispatch:
jobs:
  my-example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v3
      id: cache
      with:
        path: /tmp/datacache
        key: key-test
    - if: steps.cache.outputs.cache-hit != 'true'
      run: |
        rm -rf /tmp/datacache
        mkdir -p /tmp/datacache
        for y in {0..1};do openssl rand -out /tmp/datacache/data$y  -base64 $(( 50 * 2**20 * 3/4 )); done 
        du -sh /tmp/datacache
