name: Main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
        with:
           lfs: true
      - uses: actions/cache@v3
        id: cache
        with:
          path: name.txt
          key: ${{ runner.os }}-1
      - name: Create File
        if: steps.cache.outputs.cache-hit != 'true'
        run: echo "Hutson - ${{ github.run_id }}" > name.txt
      - run: |
          ls -lAh
          cat name.txt
