name: Test Cache download failure
on:
  workflow_dispatch:
  schedule:
  - cron: "*/5 * * * *"
jobs:
  java-example:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets:
          - path: java-example
        java_versions:
          - 11
          - 17
    steps:
    - uses: actions/cache@v3
      id: cache
      with:
        path: /tmp/datacache
        key: cache_061012
    - if: steps.cache.outputs.cache-hit != 'true'
      run: |
        rm -rf /tmp/datacache
        mkdir -p /tmp/datacache
        for y in {0..1};do openssl rand -out /tmp/datacache/data$y  -base64 $(( 50 * 2**20 * 3/4 )); done 
        du -sh /tmp/datacache
